# Generated by Django 6.1 on 2026-09-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sku_interno', models.CharField(max_length=50, unique=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('marca_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_adquisicion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5)),
                ('ubicacion_bodega', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
            ],
        ),
    ]
