# Generated by Django 5.2.17 on 2026-09-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_razon_social', models.CharField(choices=[('persona', 'Es persona'), ('empresa', 'Empresa')], default='empresa', max_length=10)),
                ('razon_social', models.CharField(max_length=200)),
                ('serial', models.CharField(max_length=100)),
                ('tipo_identificacion', models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería')], default='NIT', max_length=5)),
                ('identificacion', models.CharField(max_length=20)),
                ('digito_verificacion', models.CharField(blank=True, max_length=1, null=True, verbose_name='Dígito Verificación')),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
