# Generated by Django 5.2.17 on 2026-09-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tipo_comercio',
            field=models.CharField(choices=[('Supermercado', 'Supermercado'), ('Farmacia', 'Farmacia'), ('Ropa', 'Ropa'), ('Ferreteria', 'Ferretería'), ('Tecnologia', 'Tecnología'), ('Restaurante', 'Restaurante'), ('Agropecuario', 'Agropecuario'), ('Taller Mecanico', 'Taller Mecánico'), ('Insumos Limpieza', 'Insumos Limpieza')], default='Tipo de comercio', max_length=50),
        ),
    ]
